version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: rxyal/kittygram_backend:latest
    env_file: .env
    volumes:
      - media:/var/www/kittygram/media
    depends_on:
      - db
  frontend:
    tags: rxyal/kittygram_backend
    image: rxyal/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: rxyal/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/var/www/kittygram/media
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80