version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: rxyal/kittygram_backend:latest
    env_file: .env
    volumes:      
      - static:/backend_static/
      - media:/media/
    restart: always
    depends_on:
      - db
  frontend:
    image: rxyal/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: rxyal/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80